# Generated by Django 2.2.24 on 2022-01-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='handoff_to',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
