# Generated by Django 2.2.24 on 2022-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_handoff_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_sent',
            field=models.CharField(default='N', max_length=100, null=True),
        ),
    ]
